version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - pip install poetry
      - pip install poetry-plugin-export
      - poetry export -f requirements.txt -o requirements.txt --with docs,dev
      - cat requirements.txt

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py